name: grpc_flutter_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  grpc: ^4.0.1
  protobuf: ^3.1.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  protoc_plugin: ^21.1.2

flutter:
  uses-material-design: true
